steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/happymeter-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/happymeter-backend:latest'
      - './backend'
    id: 'build-backend'

  # Push the backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/happymeter-backend:$COMMIT_SHA'
    id: 'push-backend'

  # Build the frontend
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd frontend
        npm install
        npm run build
    id: 'build-frontend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'happymeter'
      - '--image=gcr.io/$PROJECT_ID/happymeter-backend:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,ADMIN_USERNAME=ADMIN_USERNAME:latest,ADMIN_PASSWORD=ADMIN_PASSWORD:latest'
      - '--add-cloudsql-instances=$_CLOUDSQL_INSTANCE'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=10'
    id: 'deploy-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/happymeter-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/happymeter-backend:latest'

substitutions:
  _REGION: europe-west3
  _CLOUDSQL_INSTANCE: ${PROJECT_ID}:${_REGION}:happymeter-db

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
